import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Card, CardBody } from '@components/ui/card';
import { Button } from '@components/ui/button';
import { Badge } from '@components/ui/badge';
import { aiRulesApi } from '@services/ai-rules-service';
import { Sparkles, Inbox, ChevronLeft, ChevronRight } from 'lucide-react';
import { formatDate } from '@utils/format';

const PAGE_SIZE = 20;

export function AiGenerationPage() {
  const [page, setPage] = useState(1);

  const { data, isLoading, isError, refetch } = useQuery({
    queryKey: ['ai-generated-questions', page],
    queryFn: () => aiRulesApi.listGeneratedQuestions({ page, limit: PAGE_SIZE }),
  });

  const questions = data?.data ?? [];
  const meta = data?.meta;

  return (
    <div className="space-y-6 animate-fade-in">
      <div>
        <h1 className="text-2xl font-bold text-text-primary">AI Question Generation</h1>
        <p className="mt-1 text-sm text-text-secondary">
          Oral-defense questions generated by AI, across all assessments
        </p>
      </div>

      <Card>
        <CardBody>
          <div className="flex items-start gap-4 rounded-lg bg-primary-50 p-4">
            <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-primary-100">
              <Sparkles className="h-5 w-5 text-primary-600" />
            </div>
            <div>
              <h3 className="text-sm font-semibold text-text-primary">How generation works</h3>
              <p className="mt-1 text-sm text-text-secondary">
                When an assessment is analyzed in the Assessment Builder, AI proposes oral-defense
                questions tailored to the scenario and tasks. The reviewed questions are stored here
                with the AI_GENERATED type once the draft is applied.
              </p>
            </div>
          </div>
        </CardBody>
      </Card>

      <Card className="!p-0">
        {isLoading ? (
          <div className="flex items-center justify-center py-16 text-sm text-text-tertiary">Loading generated questions...</div>
        ) : isError ? (
          <div className="flex flex-col items-center py-16 text-center">
            <Sparkles className="h-8 w-8 text-text-tertiary" />
            <p className="mt-3 text-sm text-text-secondary">Couldn't load generated questions.</p>
            <Button variant="secondary" size="sm" className="mt-3" onClick={() => refetch()}>
              Retry
            </Button>
          </div>
        ) : questions.length === 0 ? (
          <div className="flex flex-col items-center py-16 text-center">
            <Inbox className="h-8 w-8 text-text-tertiary" />
            <p className="mt-3 text-sm text-text-secondary">
              No AI-generated questions yet. Analyze an assessment in the Assessment Builder to generate some.
            </p>
          </div>
        ) : (
          <>
            <div className="divide-y divide-border">
              {questions.map((q) => (
                <div key={q.id} className="px-5 py-4">
                  <div className="flex items-start justify-between gap-4">
                    <div className="min-w-0">
                      <p className="text-sm text-text-primary">{q.questionText}</p>
                      <div className="mt-2 flex flex-wrap items-center gap-2">
                        <Badge variant="info" size="sm">AI_GENERATED</Badge>
                        {q.category && <Badge variant="neutral" size="sm">{q.category}</Badge>}
                        {q.timeLimitSeconds && (
                          <span className="text-xs text-text-tertiary">{q.timeLimitSeconds}s limit</span>
                        )}
                        {q.passingScore != null && (
                          <span className="text-xs text-text-tertiary">Passing: {q.passingScore}</span>
                        )}
                      </div>
                    </div>
                    <div className="shrink-0 text-right">
                      <p className="max-w-[260px] truncate text-sm font-medium text-text-secondary">{q.assessment?.title ?? '—'}</p>
                      <p className="mt-1 text-xs text-text-tertiary">
                        {formatDate(q.createdAt, { year: 'numeric', month: 'short', day: 'numeric' })}
                      </p>
                    </div>
                  </div>
                </div>
              ))}
            </div>

            {(meta?.totalPages ?? 1) > 1 && (
              <div className="flex items-center justify-between border-t border-border px-5 py-3">
                <p className="text-xs text-text-tertiary">
                  Page {meta?.page} of {meta?.totalPages} · {meta?.totalItems} questions
                </p>
                <div className="flex items-center gap-2">
                  <Button
                    variant="secondary"
                    size="sm"
                    disabled={!meta || meta.page <= 1}
                    onClick={() => setPage((p) => Math.max(1, p - 1))}
                    icon={<ChevronLeft className="h-4 w-4" />}
                  >
                    Prev
                  </Button>
                  <Button
                    variant="secondary"
                    size="sm"
                    disabled={!meta || meta.page >= meta.totalPages}
                    onClick={() => setPage((p) => Math.min(meta?.totalPages ?? p, p + 1))}
                    icon={<ChevronRight className="h-4 w-4" />}
                  >
                    Next
                  </Button>
                </div>
              </div>
            )}
          </>
        )}
      </Card>
    </div>
  );
}

export default AiGenerationPage;
